"""
docker/generate_compose.py

Generate a docker-compose file for any number of FL clients (full stack).

Usage:
    python docker/generate_compose.py --clients 5
    docker compose -f docker/docker-compose.generated.yml up --build
"""
import argparse
import os


def generate(n_clients: int, out_path: str):
    lines = [
        'version: "3.9"',
        "",
        "# Auto-generated by docker/generate_compose.py",
        f"# {n_clients} FL client(s) + Redis + dashboard API + UI",
        "",
        "x-fl-client: &fl-client",
        "  build:",
        "    context: ..",
        "    dockerfile: docker/Dockerfile.client",
        "  depends_on:",
        "    fl-server:",
        "      condition: service_healthy",
        "  networks:",
        "    - fl-net",
        "  restart: on-failure",
        "  volumes:",
        "    - ../crypto/certs/keys:/app/crypto/certs/keys:ro",
        "    - server-results:/app/results:ro",
        "  environment:",
        '    SERVER_ADDR: "fl-server:8080"',
        '    USE_CRYPTO: "${USE_CRYPTO:---crypto}"',
        '    USE_DP: "${USE_DP:---dp}"',
        '    EPSILON: "${EPSILON:-10.0}"',
        '    ROUNDS: "${ROUNDS:-10}"',
        '    MODEL_TYPE: "${MODEL_TYPE:-mlp}"',
        '    DASHBOARD_STATE_DIR: "/app/results"',
        '    ATTESTATION_RECORD_PATH: "/app/results/attestation.json"',
        "",
        "services:",
        "",
        "  redis:",
        "    image: redis:7-alpine",
        "    container_name: intelliclave-redis",
        "    networks:",
        "      - fl-net",
        "    healthcheck:",
        '      test: ["CMD", "redis-cli", "ping"]',
        "      interval: 5s",
        "      timeout: 3s",
        "      retries: 5",
        "    volumes:",
        "      - redis-data:/data",
        "",
        "  dashboard-backend:",
        "    build:",
        "      context: ..",
        "      dockerfile: dashboard/backend/Dockerfile",
        "    container_name: dashboard-backend",
        "    ports:",
        '      - "8001:8001"',
        "    depends_on:",
        "      redis:",
        "        condition: service_healthy",
        "    networks:",
        "      - fl-net",
        "    environment:",
        '      REDIS_URL: "redis://redis:6379/0"',
        '      REQUIRE_REDIS: "true"',
        '      CORS_ORIGINS: "http://localhost:3000"',
        '      DASHBOARD_STATE_DIR: "/app/results"',
        '      INFERENCE_EPSILON: "${INFERENCE_EPSILON:-4.0}"',
        '      LIFETIME_QUERY_BUDGET: "${LIFETIME_QUERY_BUDGET:-10000}"',
        '      RATE_LIMIT_MAX: "${RATE_LIMIT_MAX:-100}"',
        '      RATE_LIMIT_WINDOW: "${RATE_LIMIT_WINDOW:-60}"',
        '      REQUIRE_SEALED_CHECKPOINTS: "${REQUIRE_SEALED_CHECKPOINTS:-false}"',
        "    volumes:",
        "      - server-results:/app/results:ro",
        "      - ../results/benchmarks_baseline.json:/app/results/benchmarks_baseline.json:ro",
        "",
        "  dashboard-frontend:",
        "    build:",
        "      context: ..",
        "      dockerfile: dashboard/frontend/Dockerfile",
        "      args:",
        '        VITE_API_URL: "http://localhost:8001"',
        "    container_name: dashboard-frontend",
        "    ports:",
        '      - "3000:3000"',
        "    depends_on:",
        "      - dashboard-backend",
        "    networks:",
        "      - fl-net",
        "",
        "  fl-server:",
        "    build:",
        "      context: ..",
        "      dockerfile: docker/Dockerfile.server",
        "    container_name: fl-server",
        "    ports:",
        '      - "8080:8080"',
        "    volumes:",
        "      - server-results:/app/results",
        "      - ../crypto/certs/keys:/app/crypto/certs/keys:ro",
        "      - ../results/benchmarks_baseline.json:/app/results/benchmarks_baseline.json:ro",
        "    networks:",
        "      - fl-net",
        "    environment:",
        f'      ROUNDS: "${{ROUNDS:-10}}"',
        f'      MIN_CLIENTS: "{n_clients}"',
        '      ADDRESS: "0.0.0.0:8080"',
        '      USE_CRYPTO: "${USE_CRYPTO:---crypto}"',
        '      STRATEGY: "${STRATEGY:-fedavg}"',
        '      FRACTION_FIT: "${FRACTION_FIT:-1.0}"',
        '      ROUND_TIMEOUT: "${ROUND_TIMEOUT:-300}"',
        '      RESUME: "${RESUME:-}"',
        '      SAVE_DIR: "/app/results/fl_rounds"',
        '      DASHBOARD_STATE_DIR: "/app/results"',
        '      SEAL_REMOVE_PLAINTEXT: "${SEAL_REMOVE_PLAINTEXT:-true}"',
        "    healthcheck:",
        '      test: ["CMD", "python", "-c",',
        '             "import socket; s=socket.socket(); s.settimeout(2); s.connect((\'localhost\',8080)); s.close()"]',
        "      interval: 5s",
        "      timeout: 5s",
        "      retries: 12",
        "      start_period: 15s",
        "",
    ]

    env_block = (
        '      SERVER_ADDR: "fl-server:8080"\n'
        '      USE_CRYPTO: "${USE_CRYPTO:---crypto}"\n'
        '      USE_DP: "${USE_DP:---dp}"\n'
        '      EPSILON: "${EPSILON:-10.0}"\n'
        '      ROUNDS: "${ROUNDS:-10}"\n'
        '      MODEL_TYPE: "${MODEL_TYPE:-mlp}"\n'
        '      DASHBOARD_STATE_DIR: "/app/results"\n'
        '      ATTESTATION_RECORD_PATH: "/app/results/attestation.json"'
    )

    for i in range(1, n_clients + 1):
        lines += [
            f"  fl-client-{i}:",
            "    <<: *fl-client",
            f"    container_name: fl-client-{i}",
            "    volumes:",
            f"      - ../data/processed/client{i}.csv:/app/data/processed/client{i}.csv:ro",
            "      - ../crypto/certs/keys:/app/crypto/certs/keys:ro",
            "      - server-results:/app/results:ro",
            "    environment:",
            f'      CLIENT_ID: "{i}"',
            f'      CSV_PATH: "/app/data/processed/client{i}.csv"',
            env_block,
            "",
        ]

    lines += [
        "volumes:",
        "  server-results:",
        "    driver: local",
        "  redis-data:",
        "    driver: local",
        "",
        "networks:",
        "  fl-net:",
        "    driver: bridge",
        "    ipam:",
        "      config:",
        "        - subnet: 172.20.0.0/24",
    ]

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated: {out_path}  ({n_clients} client(s))")
    print(f"\nTo start:")
    print(f"  docker compose -f {out_path} up --build")


if __name__ == "__main__":
    _here = os.path.dirname(os.path.abspath(__file__))
    parser = argparse.ArgumentParser(
        description="Generate a docker-compose file for N FL clients."
    )
    parser.add_argument("--clients", type=int, default=3,
                        help="Number of FL clients (default: 3).")
    parser.add_argument(
        "--out",
        default=os.path.join(_here, "docker-compose.generated.yml"),
        help="Output path for the generated compose file.",
    )
    args = parser.parse_args()
    generate(args.clients, args.out)
