"""
docker/generate_compose.py

Generate a docker-compose file for any number of FL clients.

Usage:
    python docker/generate_compose.py --clients 5
    python docker/generate_compose.py --clients 3 --out docker/docker-compose.generated.yml

Then run:
    docker compose -f docker/docker-compose.generated.yml up --build

Environment variables honoured at runtime (pass via shell or .env file):
    USE_CRYPTO   : "--crypto" | ""          (default: --crypto)
    USE_DP       : "--dp" | ""              (default: --dp)
    EPSILON      : float                    (default: 10.0)
    ROUNDS       : int                      (default: 10)
    STRATEGY     : fedavg | fedprox         (default: fedavg)
    FRACTION_FIT : float 0-1                (default: 1.0)
    MODEL_TYPE   : mlp | resnet-tabular | transformer-tabular  (default: mlp)
"""
import argparse
import os


def generate(n_clients: int, out_path: str):
    lines = [
        'version: "3.9"',
        "",
        "# Auto-generated by docker/generate_compose.py",
        f"# {n_clients} FL client(s)",
        "",
        "services:",
        "",
        "  fl-server:",
        "    build:",
        "      context: ..",
        "      dockerfile: docker/Dockerfile.server",
        "    container_name: fl-server",
        "    ports:",
        '      - "8080:8080"',
        "    volumes:",
        "      - server-results:/app/results",
        "      - ../crypto/certs/keys:/app/crypto/certs/keys",
        "      - ../data/processed:/app/data/processed:ro",
        "    networks:",
        "      - fl-net",
        "    environment:",
        f'      ROUNDS:        "${{ROUNDS:-10}}"',
        f'      MIN_CLIENTS:   "{n_clients}"',
        '      ADDRESS:       "0.0.0.0:8080"',
        '      USE_CRYPTO:    "${USE_CRYPTO:---crypto}"',
        '      STRATEGY:      "${STRATEGY:-fedavg}"',
        '      FRACTION_FIT:  "${FRACTION_FIT:-1.0}"',
        "    healthcheck:",
        '      test: ["CMD", "python", "-c",',
        '             "import socket; s=socket.socket(); s.settimeout(2); s.connect((\'localhost\',8080)); s.close()"]',
        "      interval: 5s",
        "      timeout: 5s",
        "      retries: 12",
        "      start_period: 15s",
        "",
    ]

    for i in range(1, n_clients + 1):
        lines += [
            f"  fl-client-{i}:",
            "    build:",
            "      context: ..",
            "      dockerfile: docker/Dockerfile.client",
            f"    container_name: fl-client-{i}",
            "    depends_on:",
            "      fl-server:",
            "        condition: service_healthy",
            "    networks:",
            "      - fl-net",
            "    restart: on-failure",
            "    volumes:",
            f"      - ../data/processed/client{i}.csv:/app/data/processed/client{i}.csv:ro",
            "      - ../crypto/certs/keys:/app/crypto/certs/keys:ro",
            "    environment:",
            f'      CLIENT_ID:   "{i}"',
            f'      CSV_PATH:    "/app/data/processed/client{i}.csv"',
            '      SERVER_ADDR: "fl-server:8080"',
            '      USE_CRYPTO:  "${USE_CRYPTO:---crypto}"',
            '      USE_DP:      "${USE_DP:---dp}"',
            '      EPSILON:     "${EPSILON:-10.0}"',
            '      ROUNDS:      "${ROUNDS:-10}"',
            '      MODEL_TYPE:  "${MODEL_TYPE:-mlp}"',
            "",
        ]

    lines += [
        "volumes:",
        "  server-results:",
        "    driver: local",
        "",
        "networks:",
        "  fl-net:",
        "    driver: bridge",
        "    ipam:",
        "      config:",
        "        - subnet: 172.20.0.0/24",
    ]

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Generated: {out_path}  ({n_clients} client(s))")
    print(f"\nTo start:")
    print(f"  docker compose -f {out_path} up --build")


if __name__ == "__main__":
    _here = os.path.dirname(os.path.abspath(__file__))
    parser = argparse.ArgumentParser(
        description="Generate a docker-compose file for N FL clients."
    )
    parser.add_argument("--clients", type=int, default=3,
                        help="Number of FL clients (default: 3).")
    parser.add_argument("--out", default=os.path.join(_here, "docker-compose.generated.yml"),
                        help="Output path for the generated compose file.")
    args = parser.parse_args()
    generate(args.clients, args.out)
