apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-client-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-client-1
  template:
    metadata:
      labels:
        app: fl-client-1
    spec:
      containers:
      - name: fl-client-1
        image: fl-client-image:latest
        env:
        - name: CLIENT_ID
          value: "1"
        - name: SERVER_ADDR
          value: "fl-server-service:8080"
        - name: CSV_PATH
          value: "/app/data/processed/client1.csv"
        - name: USE_CRYPTO
          value: "--crypto"
        - name: USE_DP
          value: ""
        - name: EPSILON
          value: "10.0"
        - name: ROUNDS
          value: "10"
        volumeMounts:
        - name: client-data
          mountPath: /app/data/processed
          readOnly: true
        - name: crypto-keys
          mountPath: /app/crypto/certs/keys
          readOnly: true
      volumes:
      - name: client-data
        persistentVolumeClaim:
          claimName: client-1-pvc
      - name: crypto-keys
        secret:
          secretName: fl-crypto-keys
