apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-client-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-client-2
  template:
    metadata:
      labels:
        app: fl-client-2
    spec:
      containers:
      - name: fl-client-2
        image: fl-client-image:latest