apiVersion: v1
kind: Service
metadata:
  name: fl-server-service
  namespace: intelliclave
  labels:
    app: fl-server
spec:
  selector:
    app: fl-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP